### ISSUE TITLE
Disconnection in a few seconds

### ISSUE THREAD

**Issue by randomgoose** [dittowords/figma-plugin-react-template#1]
Hi Xavier, this project is wonderful for Figma plugin developers! Many thanks! However, I had some problems when running the code. It worked well in the first few seconds, and I can see the selected text in the browser. But then the connection was down and I got an error like this:

```
[HPM] Error occurred while trying to proxy request /favicon.ico from localhost:9000 to http://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
No issues found.
node:internal/streams/writable:304
      throw new ERR_UNKNOWN_ENCODING(encoding);
      ^

TypeError [ERR_UNKNOWN_ENCODING]: Unknown encoding: true
    at new NodeError (node:internal/errors:329:5)
    at _write (node:internal/streams/writable:304:13)
    at Socket.Writable.write (node:internal/streams/writable:345:10)
    at Sender.sendFrame (/Users/randomgoose/Documents/github/test/node_modules/ws/lib/sender.js:397:20)
    at Sender.doPing (/Users/randomgoose/Documents/github/test/node_modules/ws/lib/sender.js:188:10)
    at Sender.ping (/Users/randomgoose/Documents/github/test/node_modules/ws/lib/sender.js:174:12)
    at WebSocket.ping (/Users/randomgoose/Documents/github/test/node_modules/ws/lib/websocket.js:282:18)
    at /Users/randomgoose/Documents/github/test/preview-server.js:45:8
    at Set.forEach (<anonymous>)
    at Timeout._onTimeout (/Users/randomgoose/Documents/github/test/preview-server.js:42:15) {
  code: 'ERR_UNKNOWN_ENCODING'
}
```

**Comment by XavierAgostini** [comment]
Hey @randomgoose , I just made an update to the webpack config that should resolve this issue. Can you confirm if the issues is still occurring?

**Comment by randomgoose** [comment]
Hi Xavier, thanks for your reply! I replaced websocket with socket.io in my project and got a stable connection. Your template really helps me out. Thanks!

However, I tried the template again and still got an error:

```
node:internal/streams/writable:304
      throw new ERR_UNKNOWN_ENCODING(encoding);
      ^

TypeError [ERR_UNKNOWN_ENCODING]: Unknown encoding: true
    at new NodeError (node:internal/errors:329:5)
    at _write (node:internal/streams/writable:304:13)
    at Socket.Writable.write (node:internal/streams/writable:345:10)
    at Sender.sendFrame (/Users/randomgoose/Documents/github/figma-plugin-react-template/node_modules/ws/lib/sender.js:397:20)
    at Sender.doPing (/Users/randomgoose/Documents/github/figma-plugin-react-template/node_modules/ws/lib/sender.js:188:10)
    at Sender.ping (/Users/randomgoose/Documents/github/figma-plugin-react-template/node_modules/ws/lib/sender.js:174:12)
    at WebSocket.ping (/Users/randomgoose/Documents/github/figma-plugin-react-template/node_modules/ws/lib/websocket.js:282:18)
    at /Users/randomgoose/Documents/github/figma-plugin-react-template/preview-server.js:45:8
    at Set.forEach (<anonymous>)
    at Timeout._onTimeout (/Users/randomgoose/Documents/github/figma-plugin-react-template/preview-server.js:42:15) {
  code: 'ERR_UNKNOWN_ENCODING'
}
```

Cheers.

**Comment by XavierAgostini** [comment]
Glad you were able to use socket.io instead! I suspect it might be some compatibility issue with node.js. I'm running `v12.20.0` on my machine

**Comment by randomgoose** [comment]
Yes, I believe the problem is with nodejs. I'm closing this issue. Thanks for your help.
